"""Added link column to Todo

Revision ID: 617515daba9b
Revises: 
Create Date: 2025-01-02 20:20:59.854782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617515daba9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('sno', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('desc', sa.String(length=500), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('sno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    # ### end Alembic commands ###
