"""Added subject_name and course_name to Todo

Revision ID: e33f9c522572
Revises: 617515daba9b
Create Date: 2025-01-02 20:26:20.580773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e33f9c522572'
down_revision = '617515daba9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('course_name', sa.String(length=100), nullable=False))
        batch_op.drop_column('desc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', sa.VARCHAR(length=500), nullable=False))
        batch_op.drop_column('course_name')
        batch_op.drop_column('subject_name')

    # ### end Alembic commands ###
